services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sifa_poliklinik
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - sifa_pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=sifa_poliklinik
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

volumes:
  sifa_pgdata:
