services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sifa_poliklinik
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - sifa_pgdata:/var/lib/postgresql/data

volumes:
  sifa_pgdata:
